### ISSUE TITLE
Doesn't work via PuTTY

### ISSUE THREAD

**Issue by attie** [carlini/printf-tac-toe#5]
Before reading my issue, please know that I'm very impressed with this, and I got a lot out of reading the README - thank you / really well done!

---

I'm using PuTTY v0.73 to access an Ubuntu 18.04 machine, compiled as per the [README](https://github.com/carlini/printf-tac-toe/blob/master/README.md).

Step 1: Run, empty board is presented:

![image](https://user-images.githubusercontent.com/2195519/84024833-7ad76300-a982-11ea-976c-3424bf1de334.png)

Step 2: Enter <kbd>5</kbd> and press <kbd>Return</kbd>:

![image](https://user-images.githubusercontent.com/2195519/84025030-cdb11a80-a982-11ea-8c7c-420edbcc8bb4.png)

Step 3: Enter <kbd>1</kbd> and press <kbd>Return</kbd>:

![image](https://user-images.githubusercontent.com/2195519/84025082-e1f51780-a982-11ea-8158-7650c8c6f115.png)

---

It turns out that the string `PuTTY` is sent to `stdin`... I've never quite figured out what causes these to occur, and I've seen them in the past too - mainly when accidentally writing binary data to `stdout`.

If I remove the `PuTTY` input with 5x <kbd>Backspace</kbd> then I can play the game... if I'm lucky...

---

However, I also notice that playing the following game, results in some "_invisible_" characters in the input buffer, allowing me to press backspace, and get the cursor to wrap back on to the previous line:

`5`, `1`, `7`, `3`

![image](https://user-images.githubusercontent.com/2195519/84026057-8592f780-a984-11ea-828f-b58dec8a346c.png)

If I _do_ clear this "_invisible_" input, then the following game runs to completion:

`5`, `1`, `7`, `3`, `2`, `8`, `4`, `6`, `9`

![image](https://user-images.githubusercontent.com/2195519/84026230-da367280-a984-11ea-86d9-f2b07b5792c0.png)

If I _don't_ clear this "_invisible_" intput (i.e: I only press 5x <kbd>Backspace</kbd> to remove the `PuTTY`, or multiple thereof), then the game goes wonky... it may run to the end, or it may make wrong statements.

![image](https://user-images.githubusercontent.com/2195519/84026524-621c7c80-a985-11ea-9d7a-120b8139e188.png)

---

I suspect that this "_invisible_" input is also related to PuTTY, hence putting all of this in a single issue.

**Comment by attie** [comment]
I dug and resolved my own issue... and thought I'd share!

Using `script` to capture the output, I can see that there is a lot of binary data written to `stdout` while drawing the board... I'm not entirely sure if this is expected behaviour.

With `script` running, start `printtt`, place P1's first move in `5`, then `^C` / `SIGINT` to stop `printtt`, and then `^D` / `exit` to stop script.

Iterating through the `typescript` output (I can share if you'd like a copy), I've narrowed the issue down to writing a raw `0x05` to `stdout` / PuTTY:

![image](https://user-images.githubusercontent.com/2195519/84028330-6a29eb80-a988-11ea-97e1-7b064781e0c9.png)

It turns out that PuTTY will helpfully "_answer back to `^E`_" ... Clearing this response results in a functional and seemingly happy printf-tac-toe

![image](https://user-images.githubusercontent.com/2195519/84028690-14097800-a989-11ea-8856-9d21d13d5377.png)

---

Note: the [PuTTY FAQ](https://www.chiark.greenend.org.uk/~sgtatham/putty/faq.html#faq-puttyputty) says: "_writing binary files to your terminal is likely to cause various other unpleasant behaviour_", and I would expect that other terminal emulators will have issues with the binary output too...

**Comment by carlini** [comment]
Thanks for figuring this out---I don't think I would have got that.

**Comment by attie** [comment]
Ha, no problem!

Not sure if you're able to do anything about the binary output (or if it's important)... others may have issues too - not just PuTTY users.
