### ISSUE TITLE
Placing on an occupied square leads to unexpected behaviour

### ISSUE THREAD

**Issue by omenjohn** [carlini/printf-tac-toe#9]
Posting on behalf of a friend:

> There is a bug in the tic-tac-toe game.  P1 wins if either player plays their piece on an occupied square.
> Gotta use that GItHub "blame" button

**Comment by carlini** [comment]
Huh. Could you post steps to reproduce? On my machine when I run `echo "1 2 2" | ./prog` I would expect the third move by P1 to be invalid and then for P2 to win, and that's what happens:
```
X|?| 
-----
 | | 
-----
 | | 
P2 WINS
```

**Comment by omenjohn** [comment]
I asked the original tester if they were aware of the rules, and apparently, they were not.  I did not test this myself.  Sorry for the scare!
